FROM ubuntu:24.04

# Extend and update the package registry
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      ca-certificates \
      curl \
      wget \
      gpg \
      binutils \
      g++ \
      gcc \
      libc-dev \
      make \
      git \
      gfortran-12 \
      gfortran-13 \
      gfortran-14 \
      libnetcdff-dev

# Install Python
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      python-is-python3 \
      python3 \
      python3-pip \
 && rm -rf /var/lib/apt/lists/*

# Install packages from build/environment.yml 
RUN pip3 install  --break-system-packages \
      netCDF4 \
      cartopy \ 
      matplotlib
