#
# Install NetCDF Fortran and its dependencies
#

ARG TOOLCHAIN
FROM minimal-toolchain:$TOOLCHAIN

# Install the dependencies
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive apt-get --yes install --no-install-recommends \
      curl \
      libnetcdf-dev \
 && rm -rf /var/lib/apt/lists/*

# Install NetCDF Fortran
#   The version must be compitible with NetCDF C installed above
ARG NFVERSION=4.5.4
RUN curl https://downloads.unidata.ucar.edu/netcdf-fortran/$NFVERSION/netcdf-fortran-$NFVERSION.tar.gz | tar xz \
  && cd netcdf-fortran-$NFVERSION \
  && { ./configure \
         CFLAGS='-O2' \
         FCFLAGS='-O2 -fPIC' \
         --disable-static || \
       { cat ./config.log; exit 1; } } 
RUN cd netcdf-fortran-$NFVERSION \
  && make -j \
  && make install \
  && cd .. \
  && rm -rf netcdf-fortran-$NFVERSION \
  && ldconfig
