        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 19 13:15:48 2015
        MODULE PF_TO_MR__genmod
          INTERFACE 
            SUBROUTINE PF_TO_MR(NPOINTS,NLEV,NCOL,RAIN_LS,SNOW_LS,      &
     &GRPL_LS,RAIN_CV,SNOW_CV,PREC_FRAC,P,T,MX_RAIN_LS,MX_SNOW_LS,      &
     &MX_GRPL_LS,MX_RAIN_CV,MX_SNOW_CV)
              INTEGER(KIND=4) :: NCOL
              INTEGER(KIND=4) :: NLEV
              INTEGER(KIND=4) :: NPOINTS
              REAL(KIND=4) :: RAIN_LS(NPOINTS,NLEV)
              REAL(KIND=4) :: SNOW_LS(NPOINTS,NLEV)
              REAL(KIND=4) :: GRPL_LS(NPOINTS,NLEV)
              REAL(KIND=4) :: RAIN_CV(NPOINTS,NLEV)
              REAL(KIND=4) :: SNOW_CV(NPOINTS,NLEV)
              REAL(KIND=4) :: PREC_FRAC(NPOINTS,NCOL,NLEV)
              REAL(KIND=4) :: P(NPOINTS,NLEV)
              REAL(KIND=4) :: T(NPOINTS,NLEV)
              REAL(KIND=4) :: MX_RAIN_LS(NPOINTS,NCOL,NLEV)
              REAL(KIND=4) :: MX_SNOW_LS(NPOINTS,NCOL,NLEV)
              REAL(KIND=4) :: MX_GRPL_LS(NPOINTS,NCOL,NLEV)
              REAL(KIND=4) :: MX_RAIN_CV(NPOINTS,NCOL,NLEV)
              REAL(KIND=4) :: MX_SNOW_CV(NPOINTS,NCOL,NLEV)
            END SUBROUTINE PF_TO_MR
          END INTERFACE 
        END MODULE PF_TO_MR__genmod
