        !COMPILER-GENERATED INTERFACE MODULE: Thu Mar 19 13:15:07 2015
        MODULE PREC_SCOPS__genmod
          INTERFACE 
            SUBROUTINE PREC_SCOPS(NPOINTS,NLEV,NCOL,LS_P_RATE,CV_P_RATE,&
     &FRAC_OUT,PREC_FRAC)
              INTEGER(KIND=4) :: NCOL
              INTEGER(KIND=4) :: NLEV
              INTEGER(KIND=4) :: NPOINTS
              REAL(KIND=4) :: LS_P_RATE(NPOINTS,NLEV)
              REAL(KIND=4) :: CV_P_RATE(NPOINTS,NLEV)
              REAL(KIND=4) :: FRAC_OUT(NPOINTS,NCOL,NLEV)
              REAL(KIND=4) :: PREC_FRAC(NPOINTS,NCOL,NLEV)
            END SUBROUTINE PREC_SCOPS
          END INTERFACE 
        END MODULE PREC_SCOPS__genmod
